FROM ubuntu
RUN apt-get update
RUN apt-get -y install python-pip python-dev \
   libpq-dev libmysqlclient-dev libpq-dev \
   git libffi-dev 
RUN git clone https://github.com/telefonicaid/fiware-facts /opt/fiware-facts
WORKDIR /opt/fiware-facts/tests/acceptance
RUN pip install -r requirements.txt --allow-all-external
COPY settings.json conf/settings.json
RUN mkdir /etc/fiware.d/
COPY fiware-facts.cfg /etc/fiware.d/fiware-facts.cfg
COPY start_acceptance.sh start_acceptance.sh
CMD ./start_acceptance.sh
