FROM ubuntu
RUN apt-get update
RUN sudo apt-get -y install  python-dev \
   libpq-dev libmysqlclient-dev libpq-dev \
   git curl libffi-dev zip python-mysqldb mysql-server\
   supervisor python-clips build-essential gcc
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py 
RUN git clone https://github.com/telefonicaid/fiware-facts /opt/fiware-facts
WORKDIR /opt/fiware-facts
RUN sudo mkdir /etc/fiware.d/
RUN sudo mkdir /var/log/fiware-facts
RUN pip install -r requirements.txt
RUN pip install MySQL-python
COPY config.py facts/config.py
COPY fiware-facts.cfg /etc/fiware.d/fiware-facts.cfg
COPY start.sh start.sh
COPY config.py facts_conf/config.py
CMD ./start.sh
